// Runs as part of the Vercel build (see the "vercel-build" script in
// package.json) to build a fresh LibreOffice sandbox snapshot and bake its
// ID into src/lib/libreoffice-snapshot.generated.ts, so every deployment
// ships with a snapshot that matches its own LO_DEPS — no more manually
// re-running create-libreoffice-snapshot.ts and updating a Vercel env var
// after touching fonts/deps.
//
// Never fails the build: if snapshot creation errors for any reason (sandbox
// API hiccup, no credentials in this build environment, etc.), it logs a
// warning and leaves the generated file as-is. docx-to-pdf.ts falls back to
// LIBREOFFICE_SANDBOX_SNAPSHOT_ID or a from-scratch install when the
// generated ID is missing, so this is a soft failure, not an outage.
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { buildLibreOfficeSnapshot } from "./build-libreoffice-snapshot";

const GENERATED_FILE = path.join(
  import.meta.dirname,
  "../src/lib/libreoffice-snapshot.generated.ts"
);

async function writeSnapshotId(snapshotId: string | undefined) {
  const value = snapshotId ? JSON.stringify(snapshotId) : "undefined";
  await writeFile(
    GENERATED_FILE,
    `// Generated by scripts/write-libreoffice-snapshot.ts during the Vercel build.\n` +
      `// See that file and src/lib/libreoffice-deps.ts for context.\n` +
      `export const LIBREOFFICE_SNAPSHOT_ID: string | undefined = ${value};\n`
  );
}

async function main() {
  if (process.env.LOCAL_MODE === "true") {
    console.log("[libreoffice-snapshot] LOCAL_MODE is set, skipping (no sandbox is used).");
    return;
  }

  try {
    const snapshotId = await buildLibreOfficeSnapshot();
    await writeSnapshotId(snapshotId);
    console.log(`[libreoffice-snapshot] Wrote fresh snapshot ID: ${snapshotId}`);
  } catch (err) {
    console.warn(
      "[libreoffice-snapshot] Failed to build a fresh snapshot for this deployment; " +
        "falling back to LIBREOFFICE_SANDBOX_SNAPSHOT_ID / a from-scratch install at runtime.",
      err
    );
  }
}

main();
